<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>com.fpetrola</groupId>
        <artifactId>devices</artifactId>
        <version>0.0.2-alu-SNAPSHOT</version>
    </parent>

    <artifactId>device-plusd</artifactId>
    <packaging>jar</packaging>

    <name>+D</name>
    <dependencies>
        <dependency>
            <groupId>com.fpetrola</groupId>
            <artifactId>devices-kit</artifactId>
            <version>${project.version}</version>
        </dependency>
        <!-- The +D has a printer port on its back, and this is the printer that goes on it. -->
        <dependency>
            <groupId>com.fpetrola</groupId>
            <artifactId>device-parallel-printer</artifactId>
            <version>${project.version}</version>
        </dependency>
    </dependencies>
</project>
