/*
 * Copyright (c) 2023-2026 Fernando Damian Petrola
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <https://www.gnu.org/licenses/>.
 */

//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.2 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2025.08.20 at 03:51:45 PM ART 
//


package com.fpetrola.oozx.speccy.modules.tape;

import com.google.inject.Singleton;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for TapeSettingsType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="TapeSettingsType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="enableLoadTraps" type="{http://www.w3.org/2001/XMLSchema}boolean"/&gt;
 *         &lt;element name="accelerateLoading" type="{http://www.w3.org/2001/XMLSchema}boolean"/&gt;
 *         &lt;element name="enableSaveTraps" type="{http://www.w3.org/2001/XMLSchema}boolean"/&gt;
 *         &lt;element name="highSamplingFreq" type="{http://www.w3.org/2001/XMLSchema}boolean"/&gt;
 *         &lt;element name="flashLoad" type="{http://www.w3.org/2001/XMLSchema}boolean"/&gt;
 *         &lt;element name="autoLoadTape" type="{http://www.w3.org/2001/XMLSchema}boolean"/&gt;
 *         &lt;element name="invertedEar" type="{http://www.w3.org/2001/XMLSchema}boolean"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "TapeSettingsType", propOrder = {
    "enableLoadTraps",
    "accelerateLoading",
    "enableSaveTraps",
    "highSamplingFreq",
    "flashLoad",
    "autoLoadTape",
    "invertedEar"
})
@Singleton
public class TapeSettingsType {

    @XmlElement(defaultValue = "true")
    protected boolean enableLoadTraps;
    @XmlElement(defaultValue = "true")
    protected boolean accelerateLoading;
    @XmlElement(defaultValue = "true")
    protected boolean enableSaveTraps;
    @XmlElement(defaultValue = "false")
    protected boolean highSamplingFreq;
    @XmlElement(defaultValue = "false")
    protected boolean flashLoad;
    @XmlElement(defaultValue = "true")
    protected boolean autoLoadTape;
    @XmlElement(defaultValue = "false")
    protected boolean invertedEar;

    /**
     * Gets the value of the enableLoadTraps property.
     * 
     */
    public boolean isEnableLoadTraps() {
        return enableLoadTraps;
    }

    /**
     * Sets the value of the enableLoadTraps property.
     * 
     */
    public void setEnableLoadTraps(boolean value) {
        this.enableLoadTraps = value;
    }

    /**
     * Gets the value of the accelerateLoading property.
     * 
     */
    public boolean isAccelerateLoading() {
        return accelerateLoading;
    }

    /**
     * Sets the value of the accelerateLoading property.
     * 
     */
    public void setAccelerateLoading(boolean value) {
        this.accelerateLoading = value;
    }

    /**
     * Gets the value of the enableSaveTraps property.
     * 
     */
    public boolean isEnableSaveTraps() {
        return enableSaveTraps;
    }

    /**
     * Sets the value of the enableSaveTraps property.
     * 
     */
    public void setEnableSaveTraps(boolean value) {
        this.enableSaveTraps = value;
    }

    /**
     * Gets the value of the highSamplingFreq property.
     * 
     */
    public boolean isHighSamplingFreq() {
        return highSamplingFreq;
    }

    /**
     * Sets the value of the highSamplingFreq property.
     * 
     */
    public void setHighSamplingFreq(boolean value) {
        this.highSamplingFreq = value;
    }

    /**
     * Gets the value of the flashLoad property.
     * 
     */
    public boolean isFlashLoad() {
        return flashLoad;
    }

    /**
     * Sets the value of the flashLoad property.
     * 
     */
    public void setFlashLoad(boolean value) {
        this.flashLoad = value;
    }

    /**
     * Gets the value of the autoLoadTape property.
     * 
     */
    public boolean isAutoLoadTape() {
        return autoLoadTape;
    }

    /**
     * Sets the value of the autoLoadTape property.
     * 
     */
    public void setAutoLoadTape(boolean value) {
        this.autoLoadTape = value;
    }

    /**
     * Gets the value of the invertedEar property.
     * 
     */
    public boolean isInvertedEar() {
        return invertedEar;
    }

    /**
     * Sets the value of the invertedEar property.
     * 
     */
    public void setInvertedEar(boolean value) {
        this.invertedEar = value;
    }

}
