<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>com.fpetrola</groupId>
        <artifactId>machine</artifactId>
        <version>0.0.2-alu-SNAPSHOT</version>
    <relativePath>../../pom.xml</relativePath>
    </parent>

    <artifactId>device-memory</artifactId>
    <packaging>jar</packaging>

    <name>Memory paging of the 128K and +3</name>
    <dependencies>
        <dependency>
            <groupId>com.fpetrola</groupId>
            <artifactId>core</artifactId>
            <version>${project.version}</version>
        </dependency>
        <dependency>
            <groupId>org.junit.jupiter</groupId>
            <artifactId>junit-jupiter</artifactId>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>com.fpetrola</groupId>
            <artifactId>core</artifactId>
            <version>${project.version}</version>
            <type>test-jar</type>
            <scope>test</scope>
        </dependency>
    </dependencies>
</project>
